# Generated by Django 2.2.9 on 2020-01-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trionyx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('verbose_name', models.TextField(blank=True, default='', verbose_name='Verbose name')),
                ('item_type', models.IntegerField(blank=True, choices=[(10, 'Feature'), (20, 'Enhancement'), (30, 'Task'), (40, 'Bug'), (50, 'Question')], default=10)),
                ('priority', models.IntegerField(blank=True, choices=[(50, 'Highest'), (40, 'High'), (30, 'Medium'), (20, 'Low'), (10, 'Lowest')], default=30)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('completed_on', models.DateField(blank=True, default=None, null=True)),
                ('estimate', trionyx.models.PriceField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('non_billable', models.BooleanField(blank=True, default=False)),
                ('total_worked', models.FloatField(blank=True, default=0.0)),
                ('total_billed', models.FloatField(blank=True, default=0.0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('verbose_name', models.TextField(blank=True, default='', verbose_name='Verbose name')),
                ('date', models.DateField()),
                ('worked', models.FloatField()),
                ('billed', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='trionyx_projects.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('verbose_name', models.TextField(blank=True, default='', verbose_name='Verbose name')),
                ('for_object_id', models.BigIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField(choices=[(10, 'Draft'), (10, 'Active'), (10, 'On hold'), (10, 'Completed'), (10, 'Canceled')], default=10)),
                ('project_type', models.IntegerField(choices=[(10, 'Fixed'), (20, 'Hourly based')], default=10)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('started_on', models.DateField(blank=True, default=None, null=True)),
                ('completed_on', models.DateField(blank=True, default=None, null=True)),
                ('fixed_price', trionyx.models.PriceField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('hourly_rate', trionyx.models.PriceField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('item_increment_id', models.IntegerField(default=0)),
                ('open_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('total_items_estimate', models.FloatField(default=0.0)),
                ('total_worked', models.FloatField(default=0.0)),
                ('total_billed', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('for_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Object type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trionyx_projects.Project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('verbose_name', models.TextField(blank=True, default='', verbose_name='Verbose name')),
                ('comment', models.TextField(default='')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trionyx_projects.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
