# Generated by Django 2.2.6 on 2020-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx_projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hourly_rate',
            new_name='project_hourly_rate',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Active'), (30, 'On hold'), (40, 'Completed'), (99, 'Canceled')], default=10),
        ),
    ]
