# Generated by Django 2.2.6 on 2020-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx_projects', '0002_auto_20200415_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AlterField(
            model_name='item',
            name='estimate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
