# Generated by Django 2.2.6 on 2020-04-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx_projects', '0005_auto_20200418_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('limit_add_item', 'Limit add'), ('limit_change_item', 'Limit change'))},
        ),
    ]
